spring:
  application:
    name: review
  profiles:
    active: local
  config:
    import: optional:configserver:http://130.162.136.116:8888

---
spring:
  application:
    name: review
  profiles:
    active: test
  config:
    import: optional:configserver:http://130.162.136.116:8888
